apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: The sonarqube scanner slave image for dotnet core with the global
      sonarscanner installed.
    iconClass: icon-jenkins
    tags: jenkins,slave,sonarqube,dotnet,sonarscanner
  creationTimestamp: null
  name: jenkins-slave-sonarqube-dotnet
  selfLink: /apis/template.openshift.io/v1/namespaces/cicd/templates/jenkins-slave-sonarqube-dotnet
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${IMAGE_NAME}
  spec:
    env:
    - name: GIT_SSL_NO_VERIFY
      value: ${GIT_SSL_NO_VERIFY}
    output:
      to:
        kind: ImageStreamTag
        name: ${IMAGE_NAME}:${IMAGE_STREAM_TAG}
    source:
      contextDir: ${GIT_CONTEXT_DIR}
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_URL}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: ${DOCKERFILE_PATH}
        env:
        - name: GIT_SSL_NO_VERIFY
          value: ${GIT_SSL_NO_VERIFY}
        from:
          kind: DockerImage
          name: ${BASE_IMAGE}
      type: Docker
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${IMAGE_NAME}
parameters:
- description: The URL of the repository with your application source code
  name: GIT_URL
  required: true
  value: https://github.com/fabiovolpini/dotnet-jenkins-slave.git
- description: The branch within the repository which contains the applicable source
    code
  name: GIT_BRANCH
  required: true
  value: master
- description: The sub directory location of the docker file
  name: GIT_CONTEXT_DIR
  value: 2.2/
- description: The path to the dockerfile to use when building the image.
  name: DOCKERFILE_PATH
  required: true
  value: Dockerfile.rhel7
- description: The name of the image to make a Jenkins slave.
  name: BASE_IMAGE
  required: true
  value: openshift3/jenkins-slave-base-rhel7:latest
- description: The name of the image this build will produce
  name: IMAGE_NAME
  required: true
  value: jenkins-slave-sonarqube-dotnet
- description: The tag to associate with the image
  name: IMAGE_STREAM_TAG
  required: true
  value: latest
- name: GIT_SSL_NO_VERIFY
  required: true
  value: "true"
